// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20bBaNuNFpFQAZ1KbvBNy8nPnGPZLt0Q',
    appId: '1:478454158562:web:03445a88a34d15ebe9fabb',
    messagingSenderId: '478454158562',
    projectId: 'helpdesk-support-request',
    authDomain: 'helpdesk-support-request.firebaseapp.com',
    storageBucket: 'helpdesk-support-request.firebasestorage.app',
    measurementId: 'G-ZF9MQNHJSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGsMIRtNesPAR5fp9nCnfNMs-QWyli37M',
    appId: '1:478454158562:android:9ec3fb273b7229aae9fabb',
    messagingSenderId: '478454158562',
    projectId: 'helpdesk-support-request',
    storageBucket: 'helpdesk-support-request.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUAR-3c3YAWo4lAlIWmdNi-TOGW_-lzz4',
    appId: '1:478454158562:ios:21636202de7fce64e9fabb',
    messagingSenderId: '478454158562',
    projectId: 'helpdesk-support-request',
    storageBucket: 'helpdesk-support-request.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUAR-3c3YAWo4lAlIWmdNi-TOGW_-lzz4',
    appId: '1:478454158562:ios:21636202de7fce64e9fabb',
    messagingSenderId: '478454158562',
    projectId: 'helpdesk-support-request',
    storageBucket: 'helpdesk-support-request.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA20bBaNuNFpFQAZ1KbvBNy8nPnGPZLt0Q',
    appId: '1:478454158562:web:559c67a2985b24bbe9fabb',
    messagingSenderId: '478454158562',
    projectId: 'helpdesk-support-request',
    authDomain: 'helpdesk-support-request.firebaseapp.com',
    storageBucket: 'helpdesk-support-request.firebasestorage.app',
    measurementId: 'G-LLWZ98X4YY',
  );

}